"""initial vesper schemas

Revision ID: c2525e68347f
Revises: 
Create Date: 2026-08-01 17:01:40.554016
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2525e68347f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for schema in ("relationship", "journal", "study", "finance", "graph", "hermes"):
        op.execute(f'CREATE SCHEMA IF NOT EXISTS {schema}')
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=40), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=True),
    sa.Column('outputs_json', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_table('dashboard_summary',
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('macro_snapshot', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('date'),
    schema='finance'
    )
    op.create_table('dataset_registry',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('universe_size', sa.Integer(), nullable=True),
    sa.Column('nifty500_membership_json', sa.Text(), nullable=True),
    sa.Column('macro_snapshot_json', sa.Text(), nullable=True),
    sa.Column('feature_store_version', sa.String(length=100), nullable=True),
    sa.Column('factor_engine_version', sa.String(length=100), nullable=True),
    sa.Column('duckdb_version', sa.String(length=100), nullable=True),
    sa.Column('parquet_hashes_json', sa.Text(), nullable=True),
    sa.Column('git_commit', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    schema='finance'
    )
    op.create_table('divergence_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('as_of', sa.String(length=40), nullable=False),
    sa.Column('expected_json', sa.Text(), nullable=False),
    sa.Column('actual_json', sa.Text(), nullable=False),
    sa.Column('tracking_error', sa.Float(), nullable=True),
    sa.Column('prediction_error', sa.Float(), nullable=True),
    sa.Column('drift', sa.Float(), nullable=True),
    sa.Column('alert', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_table('experiments_index',
    sa.Column('experiment_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id'),
    schema='finance'
    )
    op.create_table('freeze_versions',
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('frozen_date', sa.String(length=40), nullable=False),
    sa.Column('git_commit', sa.String(length=100), nullable=False),
    sa.Column('experiment_id', sa.String(length=100), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('manual_approved', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('strategy_id', 'version', name='pk_freeze_versions'),
    schema='finance'
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_table('model_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_uuid', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('at', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_table('model_registry',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('parent_uuid', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('promoted_at', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('paper_perf_json', sa.Text(), nullable=True),
    sa.Column('git_commit', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('frozen', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    schema='finance'
    )
    op.create_table('notebook_entries',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('dataset_uuid', sa.String(length=100), nullable=True),
    sa.Column('strategy_uuid', sa.String(length=100), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('validation', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('final_status', sa.String(length=30), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_table('paper_account',
    sa.Column('trader_id', sa.String(length=100), nullable=False),
    sa.Column('available_cash', sa.Float(), nullable=False),
    sa.Column('settled_cash', sa.Float(), nullable=False),
    sa.Column('blocked_cash', sa.Float(), nullable=False),
    sa.Column('pending_settlements', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('trader_id'),
    schema='finance'
    )
    op.create_table('paper_holdings',
    sa.Column('trader_id', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('buy_date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('trader_id', 'ticker', name='pk_paper_holdings'),
    schema='finance'
    )
    op.create_table('paper_nav_history',
    sa.Column('trader_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('holdings_value', sa.Float(), nullable=True),
    sa.Column('n_positions', sa.Integer(), nullable=True),
    sa.Column('day_pnl_pct', sa.Float(), nullable=True),
    sa.Column('cumulative_pnl_pct', sa.Float(), nullable=True),
    sa.Column('unrealized_stcg', sa.Float(), nullable=True),
    sa.Column('unrealized_ltcg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('trader_id', 'date', name='pk_paper_nav_history'),
    schema='finance'
    )
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=100), nullable=True),
    sa.Column('trader_id', sa.String(length=100), nullable=False),
    sa.Column('trade_date', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('signal_price', sa.Float(), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=True),
    sa.Column('cost_total', sa.Float(), nullable=True),
    sa.Column('cost_breakdown', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('tax_type', sa.String(length=20), nullable=True),
    sa.Column('order_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id'),
    schema='finance'
    )
    op.create_table('research_experiments',
    sa.Column('experiment_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('git_commit', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('superseded_by', sa.String(length=100), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('paper_days', sa.Integer(), nullable=True),
    sa.Column('manual_approved', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id'),
    schema='finance'
    )
    op.create_table('graph_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('ref_table', sa.String(length=100), nullable=True),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('betweenness_score', sa.Float(), nullable=True),
    sa.Column('community_id', sa.String(length=100), nullable=True),
    sa.Column('fx', sa.Float(), nullable=True),
    sa.Column('fy', sa.Float(), nullable=True),
    sa.Column('fz', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='graph'
    )
    op.create_index(op.f('ix_graph_graph_nodes_entity_type'), 'graph_nodes', ['entity_type'], unique=False, schema='graph')
    op.create_index('ix_graph_nodes_entity', 'graph_nodes', ['entity_type', 'ref_id'], unique=False, schema='graph')
    op.create_table('graph_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='graph'
    )
    op.create_index(op.f('ix_graph_graph_snapshots_as_of'), 'graph_snapshots', ['as_of'], unique=False, schema='graph')
    op.create_table('hermes_llm_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hermes'
    )
    op.create_index('ix_hermes_llm_usage_ts', 'hermes_llm_usage', ['ts'], unique=False, schema='hermes')
    op.create_table('hermes_tool_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('agent_tool_id', sa.String(length=200), nullable=True),
    sa.Column('tool_name', sa.String(length=200), nullable=False),
    sa.Column('server_name', sa.String(length=100), nullable=True),
    sa.Column('inputs_json', sa.JSON(), nullable=True),
    sa.Column('outputs_json', sa.JSON(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hermes'
    )
    op.create_index('ix_hermes_tool_calls_ts', 'hermes_tool_calls', ['ts'], unique=False, schema='hermes')
    op.create_table('diary_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('category', sa.Enum('STUDY', 'HOBBY', 'GENERAL', name='diarycategory'), nullable=False),
    sa.Column('vault_path', sa.String(length=1000), nullable=True),
    sa.Column('mood', sa.String(length=10), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='journal'
    )
    op.create_index(op.f('ix_journal_diary_entries_category'), 'diary_entries', ['category'], unique=False, schema='journal')
    op.create_index(op.f('ix_journal_diary_entries_created_at'), 'diary_entries', ['created_at'], unique=False, schema='journal')
    op.create_index(op.f('ix_journal_diary_entries_entry_date'), 'diary_entries', ['entry_date'], unique=False, schema='journal')
    op.create_table('clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('cx', sa.Float(), nullable=True),
    sa.Column('cy', sa.Float(), nullable=True),
    sa.Column('cz', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_table('cron_runs',
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('job_name'),
    schema='relationship'
    )
    op.create_table('group_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('person_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='relationship'
    )
    op.create_table('tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='study'
    )
    op.create_table('graph_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['graph.graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['graph.graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='graph'
    )
    op.create_index(op.f('ix_graph_graph_edges_source_id'), 'graph_edges', ['source_id'], unique=False, schema='graph')
    op.create_index(op.f('ix_graph_graph_edges_target_id'), 'graph_edges', ['target_id'], unique=False, schema='graph')
    op.create_table('persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hobbies', sa.JSON(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('category', sa.Enum('FAMILY', 'COUSINS', 'RELATIVES', 'FRIENDS', 'COLLEAGUES', 'NEW_CONTACT', 'NETWORK', 'IMPORTANT', name='category'), nullable=False),
    sa.Column('relation_type', sa.Enum('FAMILY', 'FRIEND', 'COLLEAGUE', 'MENTOR', 'OTHER', name='relationtype'), nullable=False),
    sa.Column('contact_frequency_days', sa.Integer(), nullable=True),
    sa.Column('last_contacted', sa.DateTime(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('anniversary', sa.DateTime(), nullable=True),
    sa.Column('introduced_by_id', sa.String(length=36), nullable=True),
    sa.Column('topics_of_interest', sa.JSON(), nullable=True),
    sa.Column('meeting_place', sa.String(length=200), nullable=True),
    sa.Column('rss_feed_url', sa.String(length=500), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('streak_weeks', sa.Integer(), nullable=False),
    sa.Column('streak_last_updated', sa.DateTime(), nullable=True),
    sa.Column('betweenness_score', sa.Float(), nullable=True),
    sa.Column('community_id', sa.String(length=100), nullable=True),
    sa.Column('profile_notes', sa.Text(), nullable=True),
    sa.Column('important_events', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('fx', sa.Float(), nullable=True),
    sa.Column('fy', sa.Float(), nullable=True),
    sa.Column('fz', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['relationship.clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['introduced_by_id'], ['relationship.persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_persons_name'), 'persons', ['name'], unique=False, schema='relationship')
    op.create_table('mock_tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('subject_scores', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['study.tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='study'
    )
    op.create_index(op.f('ix_study_mock_tests_test_id'), 'mock_tests', ['test_id'], unique=False, schema='study')
    op.create_table('gift_ideas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('price_range', sa.String(length=50), nullable=True),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('is_given', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_gift_ideas_person_id'), 'gift_ideas', ['person_id'], unique=False, schema='relationship')
    op.create_table('health_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_health_snapshots_person_id'), 'health_snapshots', ['person_id'], unique=False, schema='relationship')
    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('CALL', 'MESSAGE', 'MEETING', 'EMAIL', 'SOCIAL', 'BIRTHDAY_WISH', 'OTHER', name='interactiontype'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('follow_up_needed', sa.Boolean(), nullable=False),
    sa.Column('follow_up_note', sa.Text(), nullable=True),
    sa.Column('group_interaction_id', sa.String(length=36), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('initiated_by', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['group_interaction_id'], ['relationship.group_interactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_interactions_client_uuid'), 'interactions', ['client_uuid'], unique=True, schema='relationship')
    op.create_index(op.f('ix_relationship_interactions_person_id'), 'interactions', ['person_id'], unique=False, schema='relationship')
    op.create_table('introductions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_a_id', sa.String(length=36), nullable=False),
    sa.Column('person_b_id', sa.String(length=36), nullable=False),
    sa.Column('made_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_a_id'], ['relationship.persons.id'], ),
    sa.ForeignKeyConstraint(['person_b_id'], ['relationship.persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_introductions_person_a_id'), 'introductions', ['person_a_id'], unique=False, schema='relationship')
    op.create_index(op.f('ix_relationship_introductions_person_b_id'), 'introductions', ['person_b_id'], unique=False, schema='relationship')
    op.create_table('life_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_life_events_person_id'), 'life_events', ['person_id'], unique=False, schema='relationship')
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_notes_person_id'), 'notes', ['person_id'], unique=False, schema='relationship')
    op.create_table('person_field_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_person_field_history_person_id'), 'person_field_history', ['person_id'], unique=False, schema='relationship')
    op.create_table('person_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['relationship.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_person_tags_person_id'), 'person_tags', ['person_id'], unique=False, schema='relationship')
    op.create_index(op.f('ix_relationship_person_tags_tag_id'), 'person_tags', ['tag_id'], unique=False, schema='relationship')
    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_a_id', sa.String(length=36), nullable=False),
    sa.Column('person_b_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.Enum('STRONG', 'MEDIUM', 'WEAK', name='relationshipstrength'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_a_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_relationships_person_a_id'), 'relationships', ['person_a_id'], unique=False, schema='relationship')
    op.create_index(op.f('ix_relationship_relationships_person_b_id'), 'relationships', ['person_b_id'], unique=False, schema='relationship')
    op.create_table('reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_reminders_due_at'), 'reminders', ['due_at'], unique=False, schema='relationship')
    op.create_table('rss_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['relationship.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_rss_entries_person_id'), 'rss_entries', ['person_id'], unique=False, schema='relationship')
    op.create_table('relationship_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('relationship_id', sa.String(length=36), nullable=False),
    sa.Column('week_of', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_id', 'week_of', name='uq_relationship_week'),
    schema='relationship'
    )
    op.create_index(op.f('ix_relationship_relationship_scores_relationship_id'), 'relationship_scores', ['relationship_id'], unique=False, schema='relationship')
    op.create_index(op.f('ix_relationship_relationship_scores_week_of'), 'relationship_scores', ['week_of'], unique=False, schema='relationship')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_relationship_scores_week_of'), table_name='relationship_scores', schema='relationship')
    op.drop_index(op.f('ix_relationship_relationship_scores_relationship_id'), table_name='relationship_scores', schema='relationship')
    op.drop_table('relationship_scores', schema='relationship')
    op.drop_index(op.f('ix_relationship_rss_entries_person_id'), table_name='rss_entries', schema='relationship')
    op.drop_table('rss_entries', schema='relationship')
    op.drop_index(op.f('ix_relationship_reminders_due_at'), table_name='reminders', schema='relationship')
    op.drop_table('reminders', schema='relationship')
    op.drop_index(op.f('ix_relationship_relationships_person_b_id'), table_name='relationships', schema='relationship')
    op.drop_index(op.f('ix_relationship_relationships_person_a_id'), table_name='relationships', schema='relationship')
    op.drop_table('relationships', schema='relationship')
    op.drop_index(op.f('ix_relationship_person_tags_tag_id'), table_name='person_tags', schema='relationship')
    op.drop_index(op.f('ix_relationship_person_tags_person_id'), table_name='person_tags', schema='relationship')
    op.drop_table('person_tags', schema='relationship')
    op.drop_index(op.f('ix_relationship_person_field_history_person_id'), table_name='person_field_history', schema='relationship')
    op.drop_table('person_field_history', schema='relationship')
    op.drop_index(op.f('ix_relationship_notes_person_id'), table_name='notes', schema='relationship')
    op.drop_table('notes', schema='relationship')
    op.drop_index(op.f('ix_relationship_life_events_person_id'), table_name='life_events', schema='relationship')
    op.drop_table('life_events', schema='relationship')
    op.drop_index(op.f('ix_relationship_introductions_person_b_id'), table_name='introductions', schema='relationship')
    op.drop_index(op.f('ix_relationship_introductions_person_a_id'), table_name='introductions', schema='relationship')
    op.drop_table('introductions', schema='relationship')
    op.drop_index(op.f('ix_relationship_interactions_person_id'), table_name='interactions', schema='relationship')
    op.drop_index(op.f('ix_relationship_interactions_client_uuid'), table_name='interactions', schema='relationship')
    op.drop_table('interactions', schema='relationship')
    op.drop_index(op.f('ix_relationship_health_snapshots_person_id'), table_name='health_snapshots', schema='relationship')
    op.drop_table('health_snapshots', schema='relationship')
    op.drop_index(op.f('ix_relationship_gift_ideas_person_id'), table_name='gift_ideas', schema='relationship')
    op.drop_table('gift_ideas', schema='relationship')
    op.drop_index(op.f('ix_study_mock_tests_test_id'), table_name='mock_tests', schema='study')
    op.drop_table('mock_tests', schema='study')
    op.drop_index(op.f('ix_relationship_persons_name'), table_name='persons', schema='relationship')
    op.drop_table('persons', schema='relationship')
    op.drop_index(op.f('ix_graph_graph_edges_target_id'), table_name='graph_edges', schema='graph')
    op.drop_index(op.f('ix_graph_graph_edges_source_id'), table_name='graph_edges', schema='graph')
    op.drop_table('graph_edges', schema='graph')
    op.drop_table('tests', schema='study')
    op.drop_table('tags', schema='relationship')
    op.drop_table('push_subscriptions', schema='relationship')
    op.drop_table('group_interactions', schema='relationship')
    op.drop_table('cron_runs', schema='relationship')
    op.drop_table('clusters', schema='relationship')
    op.drop_index(op.f('ix_journal_diary_entries_entry_date'), table_name='diary_entries', schema='journal')
    op.drop_index(op.f('ix_journal_diary_entries_created_at'), table_name='diary_entries', schema='journal')
    op.drop_index(op.f('ix_journal_diary_entries_category'), table_name='diary_entries', schema='journal')
    op.drop_table('diary_entries', schema='journal')
    op.drop_index('ix_hermes_tool_calls_ts', table_name='hermes_tool_calls', schema='hermes')
    op.drop_table('hermes_tool_calls', schema='hermes')
    op.drop_index('ix_hermes_llm_usage_ts', table_name='hermes_llm_usage', schema='hermes')
    op.drop_table('hermes_llm_usage', schema='hermes')
    op.drop_index(op.f('ix_graph_graph_snapshots_as_of'), table_name='graph_snapshots', schema='graph')
    op.drop_table('graph_snapshots', schema='graph')
    op.drop_index('ix_graph_nodes_entity', table_name='graph_nodes', schema='graph')
    op.drop_index(op.f('ix_graph_graph_nodes_entity_type'), table_name='graph_nodes', schema='graph')
    op.drop_table('graph_nodes', schema='graph')
    op.drop_table('research_experiments', schema='finance')
    op.drop_table('paper_trades', schema='finance')
    op.drop_table('paper_nav_history', schema='finance')
    op.drop_table('paper_holdings', schema='finance')
    op.drop_table('paper_account', schema='finance')
    op.drop_table('notebook_entries', schema='finance')
    op.drop_table('model_registry', schema='finance')
    op.drop_table('model_history', schema='finance')
    op.drop_table('job_runs', schema='finance')
    op.drop_table('freeze_versions', schema='finance')
    op.drop_table('experiments_index', schema='finance')
    op.drop_table('divergence_metrics', schema='finance')
    op.drop_table('dataset_registry', schema='finance')
    op.drop_table('dashboard_summary', schema='finance')
    op.drop_table('audit_log', schema='finance')
    for schema in ("hermes", "graph", "study", "journal", "relationship", "finance"):
        op.execute(f'DROP SCHEMA IF EXISTS {schema} CASCADE')
    # ### end Alembic commands ###
